config/routes.rb
Rails.application.routes.draw do
  root "application#index"
  resources :articles
  resources :users, except: [:new]
  get "registrate", to: "users#new"
  get "login", to: "sessions#new"
  post "authenticate", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 10, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, uniqueness: true, presence: true, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, uniqueness: true, presence: true, length: { minimum: 0, maximum: 105 }, format: { with: VALID_EMAIL_REGEX, massage: "incorrect email address" }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    redirect_to articles_path if is_logged_in?
  end

  helper_method :current_user, :is_logged_in?, :require_user

  def current_user
    @currentUser ||= User.find(session[:user_id]) if session[:user_id]
  end

  def is_logged_in?
    !!current_user
  end

  def require_user
    if !is_logged_in?
      flash[:alert] = "You are not able to do this kind of operations since you aren't logged in"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_author, only: [:edit, :destroy, :update]

  def index
    @articles = Article.paginate(:page => params[:page], :per_page => 2)
  end

  def show
  end

  def new
    @article = Article.new()
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to article_path(@article)
    else
      render "new"
    end
  end

  def edit
    puts "hello world render edit"
  end

  def update
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_author
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can't edit artworks other than yours"
      redirect @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # before_action :require_user, except: [:index, :show]
  before_action :find_category_by_id, only: [:show]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(name: params[:category][:name])

    if @category.save
      flash[:notice] = "Category '#{@category.name}' was created successfully"
      redirect_to @category
    else
      render "new"
    end
  end

  private

  def find_category_by_id
    @category = Category.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    p params[:session][:email]
    @user = User.find_by(email: params[:session][:email])
    puts "USER:"
    p params[:password]
    if @user == nil
      flash[:alert] = "User not found"
      @user = User.new
      render "new"
      return
    end
    if @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "Invalid pass"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You was logged out successfully"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :define_user, only: [:new]
  before_action :find_user_by_id, only: [:edit, :update, :show, :destroy]
  before_action :require_author , only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(:page => params[:page], :per_page => 2)
  end

  def show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User was successfully created. #{@user.username}, Welcome to the Alpha Blog"
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User was successfuly edited"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    redirect_to root_path
  end

  private

  def define_user
    @user = User.new
  end

  def require_author
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can't edit or delete foreign accounts"
      redirect_to @user
    end
  end

  def find_user_by_id
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, size = 80)
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: "User Avatar")
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<div class="content">
    <div class="container">
        <div class="jumbotron text-center text-white d-flex">
            <h1>Alpha Blog</h1>
            <h3>Lorem ipsum dolor sit amet consectetur, adipisicing elit.</h3>
            <%= link_to "Sign up!", registrate_path, class: "btn btn-success" %>
        </div>
    </div>
</div>

app/views/articles/_form.html.erb
<%= render "shared/errors", object: @article %>

<%= form_with(model: @article, local: true, data: { turbo: false }, class: "form d-flex flex-column") do |f| %>
    <div class="mb-3 d-flex">
        <%= f.label :title, class: "form-label", id: "exampleInputEmail1" %>
        <%= f.text_field :title, class: "form-control", id: "exampleInputEmail1" %>
    </div>

    <div class="mb-3 d-flex">
        <%= f.label :description, class: "form-label", id: "exampleInputEmail1" %>
        <%= f.text_area :description, class: "form-control", id: "exampleInputEmail1", rows: "8" %>
    </div>
    <%= f.submit class: 'btn btn-outline-light form__submit-btn' %>
<% end %>

app/views/articles/edit.html.erb
    <div class="container text-center col-10">
    <h1>Edit article</h1>

<%= render "form" %>

[<%= link_to "Return to Articles page", articles_path() %>]
</div>

app/views/articles/index.html.erb
<div class="container d-flex flex-column justify-center text-center">
    <h1>All Articles</h1>
    <p><%= link_to "Create Article", new_article_path() %></p>

  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

    <%= render "shared/articlesList", articles: @articles %>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

</div>

app/views/articles/new.html.erb
    <div class="container text-center">
    <h1>Create a new article</h1>

<%= render "form" %>

[<%= link_to "Return to Articles page", articles_path() %>]
</div>

app/views/articles/show.html.erb
    <div class="container d-flex flex-column justify-center text-center">
    <h1>Article Page</h1>
        <div class="card" id="card">
            <div class="card-header d-flex flex-column">
                <%= link_to gravatar_for(@article.user, 50), user_path(@article.user), class: "mb-2" %>
                By <%= @article.user.username %>
            </div>
            <div class="card-body">
                <h5 class="card-title"><%= @article.title %></h5>
                <div class="card-text description-text"><%= simple_format(@article.description) %></div>
                <% if is_logged_in? && (@article.user === current_user || current_user.admin?) %>
                    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-warning" %>
                    <%= link_to "Delete", article_path(@article), data: { turbo_method: :delete },  class: "btn btn-outline-danger" %>
                <% end %>

            </div>
            <div class="card-footer text-muted">
               Created <%= time_ago_in_words(@article.created_at) %> ago.
               Last edited <%= time_ago_in_words(@article.updated_at) %> ago
            </div>
        </div>
    <p><%= link_to "Return to all Articles", articles_path() %></p>
</div>

app/views/categories/_form.html.erb
<%= render "shared/errors", object: @category %>

<%= form_with(model: @category, local: true, data: { turbo: false }, class: "form d-flex flex-column") do |f| %>
    <div class="mb-3 d-flex">
        <%= f.label :name, class: "form-label", id: "exampleInputName" %>
        <%= f.text_field :name, class: "form-control", id: "exampleInputName" %>
    </div>
    <%= f.submit class: 'btn btn-outline-light form__submit-btn' %>
<% end %>

app/views/categories/new.html.erb
    <div class="container text-center">
    <h1>Create a new category</h1>

<%= render "form" %>

[<%= link_to "Return to Articles page", articles_path() %>]
</div>

app/views/categories/show.html.erb
    <div class="container d-flex flex-column justify-center text-center">
    <h1>'<%= @category.name %>' category:</h1>
    <p><%= link_to "Return to all Articles", articles_path() %></p>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div>Oleg Ovramets</div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, message| %>
    <div class="alert <%= name == "notice" ? "alert-success" : "alert-danger"%> alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <%= link_to "Articles list", articles_path, class: "dropdown-item" %>
            <% if is_logged_in? %>
              <%= link_to "Create new Article", new_article_path, class: "dropdown-item" %>
            <% end %>
          </ul>
        </li>


            <% if is_logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
              </a>
              <ul class="dropdown-menu">
                <%= link_to "View profile", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item" %>
                <li><hr class="dropdown-divider"></li>
                <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", data: { turbo_method: :delete } %>
              </ul>
            </li>

            <li class="nav-item">
              <%= link_to "Logout", logout_path, class: "nav-link", data: { turbo_method: :delete } %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", login_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", registrate_path, class: "nav-link" %>
            </li>
          <% end %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <%= render "layouts/navbar" %>
    <div class="content">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
   <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_articlesList.html.erb
<% articles.each_with_index do |article, index| %>
        <div class="card text-center" id="card">
            <div class="card-header">
                By <%= link_to article.user.username, user_path(article.user) %>
            </div>
            <div class="card-body">
                <h5 class="card-title"><%= article.title %></h5>
                <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                <%= link_to "See details", article_path(article), class: "btn btn-outline-info outline" %>
                <% if is_logged_in? && (article.user === current_user || current_user.admin?) %>
                    <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-warning" %>
                    <%= link_to "Delete", article_path(article), data: { turbo_method: :delete },  class: "btn btn-outline-danger" %>
                <% end %>
            </div>
            <div class="card-footer text-muted">
               Created <%= time_ago_in_words(article.created_at) %> ago.
               Last edited <%= time_ago_in_words(article.updated_at) %> ago
            </div>
        </div>
    <% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<div class="alert alert-danger" role="alert">
    <h3>This errors prevented <%= object.class.name.downcase %> from successful creation </h3>
 <ul>
    <% object.errors.full_messages.each do |error_msg| %>
        <li style="color: red; text-align: left"><%= error_msg %></li>
    <% end %>
    </ul>
</div>

<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", object: @user %>

<%= form_with(model: @user, local: true, data: { turbo: false }, class: "form d-flex flex-column") do |f| %>
    <div class="mb-3 d-flex">
        <%= f.label :username, class: "form-label", id: "exampleInputEmail1" %>
        <%= f.text_field :username, class: "form-control", id: "exampleInputEmail1" %>
    </div>

    <div class="mb-3 d-flex">
        <%= f.label :email, class: "form-label", id: "exampleInputEmail1" %>
        <%= f.text_field :email, class: "form-control", id: "exampleInputEmail1", rows: "8" %>
    </div>

    <div class="mb-3 d-flex">
        <%= f.label :password, class: "form-label", id: "exampleInputEmail1" %>
        <%= f.password_field :password, class: "form-control", id: "exampleInputEmail1", rows: "8" %>
    </div>
    <%= f.submit(@user.new_record? ? "Sign up" : "Edit profile", class: 'btn btn-outline-light form__submit-btn') %>
<% end %>

app/views/users/edit.html.erb
<div class="container text-center">
<h1>Edit user</h1>

<%= render "form" %>

[<%= link_to "Return to articles page", articles_path %>]
</div>

app/views/users/index.html.erb
<div class="container text-center">
    <h1>All Bloggers</h1>

    <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false %>
    </div>

   <% @users.each do |user| %>
        <div class="card text-center" id="card">
            <div class="card-header">
                <%= link_to user.username, user_path(user) %>
            </div>
            <div class="card-body">
                <%= gravatar_for user, 200 %>
                <p><%= user.articles.length %> articles</p>
                <%= link_to "See details", user_path(user), class: "btn btn-outline-info outline" %>
                <% if is_logged_in? %>
                    <% if current_user == user %>
                        <%= link_to "Edit", edit_user_path(user), class: "btn btn-outline-warning" %>
                    <% end %>
                    <% if current_user.admin? %>
                        <%= link_to "Delete", user_path(user), class: "btn btn-outline-danger", data: { method: :delete } %>
                    <% end %>
                <% end %>
            </div>
            <div class="card-footer text-muted">
               Joined <%= time_ago_in_words(user.created_at) %> ago.
            </div>
        </div>
    <% end %>
    <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false %>
    </div>

</div>

app/views/users/new.html.erb
<div class="container text-center">
<h1>Sign up for alpha blog</h1>

<%= render "form" %>

[<%= link_to "Return to homepage", root_path() %>]
</div>

app/views/users/show.html.erb
<div class="container text-center">
<h1><%= "#{@user.username}'s profile" %></h1>

<%= gravatar_for(@user, 200) %>

<% if @user == current_user %>
    <div class="text-center m-4">
        <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
    </div>
<% end %>

<h1>Articles</h1>

<%= render "shared/articlesList", articles: @user.articles %>

[<%= link_to "Return to articles", articles_path %>]
</div>